---
kind: pipeline
type: kubernetes
name: default

steps:
- name: backend
  image: golang:1.18
  commands:
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - go build ./...
    - go vet ./...
    - staticcheck ./...
    - go test -race -cover ./...
